---
NAME: k8s-cluster-from-ground-up
AWS_REGION: us-west-2
KUBERNETES_API_SERVER_ADDRESS: k8s-cluster-from-ground-up-e15984f67f4716a7.elb.us-west-2.amazonaws.com
KUBERNETES_PUBLIC_ADDRESS: k8s-cluster-from-ground-up-e15984f67f4716a7.elb.us-west-2.amazonaws.com