---
- hosts: tag_Name_master_0, tag_Name_master_1, tag_Name_master_2 
- name: master nodes assignment
  import_playbook: ../static-assignments/master-nodes.yml

- hosts: tag_Name_worker_0, tag_Name_worker_1, tag_Name_worker_2
- name: worker nodes assignment
  import_playbook: ../static-assignments/worker-nodes.yml

- hosts: localhost
- name: workstation assignment
  import_playbook: ../static-assignments/workstation.yml
