---
- name: Copy binding.sh to master nodes
  template:
    src: "./templates/binding.sh.j2"
    dest: "/"
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Create and bind cluster roles
  ansible.builtin.shell: ./binding.sh
  args:
    chdir: /